server:
#  port: 8099
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  profiles:
    active: dev
  servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 2MB

#日志级别
logging:
  level:
    root:
      info

# 整合mybatis
mybatis:
  type-aliases-package: com.imooc.pojo       # 所有pojo类所在的包路径
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件

# 通用mapper工具的配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper      # 配置MyMapper，包含了一些封装好的CRUD方法
  not-empty: false                            # 在进行数据库操作的时候，username != null 是否会追加 username != ''
  identity: MYSQL

# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true